### ISSUE TITLE
issue with mount script

### ISSUE THREAD

**Issue by MartinKuhl** [mrvnklm/plex-docker-smb-mount#1]
in the docker logs I get the following error:

```Setting up cifs-utils (2:6.14-1ubuntu0.1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/cifs-utils/idmapwb.so to provide /etc/cifs-utils/idmap-plugin (idmap-plugin) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man8/idmap-plugin.8.gz because associated file /usr/share/man/man8/idmapwb.8.gz (of link group idmap-plugin) doesn't exist
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Couldn't chdir to /mnt/H341$: No such file or directory
s6-rc: warning: unable to start service init-smb-mount: command exited 1
```
any ideas?

**Comment by MartinKuhl** [comment]
here some tests:
```
root@f77a22109b80:/mnt# mount -v -t cifs //192.168.177.100/video /mnt/H341 -o username=martin,password='Macool,1988'
mount.cifs kernel mount options: ip=192.168.177.100,unc=\\192.168.177.100\video,1988,user=martin,pass=********
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

```

**Comment by mrvnklm** [comment]
I updated the script, just remove the extra `$` of the mount command in `run` like `/mnt/$SMB_SHARE$` to `/mnt/$SMB_SHARE`

**Comment by MartinKuhl** [comment]
when I use it like this:
```
mount -v -t cifs //192.168.177.100/video /mnt/H341 -o username=martin,password='xxx'
```
I get this error: mount error(22): Invalid argument

**Comment by MartinKuhl** [comment]
my password includes a , so I used a ' at the beginng and end of the password. maybe this is the problem?

**Comment by mrvnklm** [comment]
Yes thats an issues. Try `-o "username=martin,password='xxx'"`

**Comment by MartinKuhl** [comment]
no success: mount error(22): Invalid argument

**Comment by mrvnklm** [comment]
Can you post the whole file please?

**Comment by MartinKuhl** [comment]
for testing reasons I only try the mount command via portainer command shell. 
the folder /mnt/H341 is created and now try to modify the mount command to make it working with a , inside the password

**Comment by mrvnklm** [comment]
Okay I think it might not work that way, as the comma is the seperator of the argument. The easiest solution would be to adjust the password. Otherwise there is a way using a credentials file, which my approach currently does not support out of the box. See here https://unix.stackexchange.com/a/436181
I also found another bug in the script, so please update to the current version before proceeding.

**Comment by mrvnklm** [comment]
@MartinKuhl Please let me know wether you need further assistance or if you solved the issue.

**Comment by MartinKuhl** [comment]
I created a new user without special character within the pw and I updated your script and I also verified that the user is able to connect via smb.
But in the serverlogs I found the following error:  
```
mount error(113): could not connect to 192.168.177.100Unable to find suitable address.
s6-rc: warning: unable to start service init-smb-mount: command exited 32
```
The ip is reachable within my network.

**Comment by mrvnklm** [comment]
Have you tried to ping it from within the container? `docker exec -it plex /bin/bash`

**Comment by MartinKuhl** [comment]
the ping command is not available inside the container

**Comment by mrvnklm** [comment]
> the ping command is not available inside the container

`apt update && apt install -y inetutils-ping`

**Comment by MartinKuhl** [comment]
ok that is interessting the host is not reachable inside the container

**Comment by mrvnklm** [comment]
Is it reachable from within the host ssh? Is the container running with `--host`?

**Comment by MartinKuhl** [comment]
now I am total confused. Yes I started it now with --net=host and my NAS is still noch reachable. I am testing at the moment inside Docker on my Mac. But can this be an issue?

**Comment by MartinKuhl** [comment]
The container is able to access the internet but not my local network

**Comment by MartinKuhl** [comment]
Thanks for your help, I will try tomorrow again and start over.

**Comment by MartinKuhl** [comment]
I started over and now it works even with some minor adjustments.
```
--name=plex \
--net=bridge \
--restart unless-stopped \
--privileged \
-p 32400:32400 \
```

I don't know why, cause I tried the same already yesterday.

**Comment by mrvnklm** [comment]
Alright, nice. `--net=bridge` is no necessary as it is the default. Please check out the `Optional Parameters` section for other ports as you might run into issues not exposing all of them: https://hub.docker.com/r/linuxserver/plex

**Comment by MartinKuhl** [comment]
thanks the other ports are not needed for my setup and usecase therefore I looked for the bridge setup to only expose the 32400 port.
